In [1]:
import pandas as pd

# Part 1 – Load the Data

In [2]:
# Load the three coffee datasets into separate DataFrames
exports = pd.read_csv("Coffee_export-1.csv")
imports = pd.read_csv("Coffee_import-1.csv")
production = pd.read_csv("Coffee_production-1.csv")

In [3]:
# Show the first 5 rows of the data
exports.head()
imports.head()
production.head()

,Country,Coffee type,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
0,Angola,Robusta/Arabica,3.000000e+06,4.740000e+06,4.680000e+06,1.980000e+06,4.620000e+06,3.720000e+06,4.260000e+06,3.840000e+06,...,1.740000e+06,1.980000e+06,2.100000e+06,2.340000e+06,2.460000e+06,2.700000e+06,2.100000e+06,2.520000e+06,3.120000e+06,8.208000e+07
1,Bolivia (Plurinational State of),Arabica,7.380000e+06,6.240000e+06,7.200000e+06,3.060000e+06,7.020000e+06,8.520000e+06,7.500000e+06,8.460000e+06,...,7.920000e+06,6.300000e+06,7.200000e+06,6.000000e+06,5.040000e+06,4.680000e+06,5.040000e+06,4.980000e+06,4.860000e+06,2.070000e+08
2,Brazil,Arabica/Robusta,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10
3,Burundi,Arabica/Robusta,2.922000e+07,4.002000e+07,3.720000e+07,2.358000e+07,3.984000e+07,2.604000e+07,2.406000e+07,1.500000e+07,...,1.224000e+07,2.436000e+07,9.780000e+06,1.488000e+07,1.614000e+07,1.176000e+07,1.212000e+07,1.224000e+07,1.632000e+07,6.236400e+08
4,Ecuador,Arabica/Robusta,9.024000e+07,1.274400e+08,7.110000e+07,1.241400e+08,1.425600e+08,1.132800e+08,1.195800e+08,7.146000e+07,...,4.950000e+07,4.968000e+07,3.996000e+07,3.864000e+07,3.864000e+07,3.870000e+07,3.744000e+07,2.976000e+07,3.354000e+07,1.900380e+09

# Part 2 – Explore the Data

In [4]:
# Group the three DataFrames so each question can be answered for all of them in one loop
datasets = {
    "Export": exports,
    "Import": imports,
    "Production": production,
}

In [5]:
# Q1: How many rows and columns does each dataset contain?
for name, df in datasets.items():
    print(f"{name}: {df.shape[0]} rows, {df.shape[1]} columns")

Export: 55 rows, 32 columns
Import: 35 rows, 32 columns
Production: 55 rows, 33 columns

In [6]:
# Q2: What are the column names?
for name, df in datasets.items():
    print(f"--- {name} ---")
    print(list(df.columns))
    print()

--- Export ---
['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_export']

--- Import ---
['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', 'Total_import']

--- Production ---
['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94', '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00', '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06', '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12', '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18', '2018/19', '2019/20', 'Total_production']

In [7]:
# Q3: What data types are assigned to each column?
for name, df in datasets.items():
    print(f"========== {name} ==========")
    df.info()
    print()

========== Export ==========
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       55 non-null     str
 1   1990          55 non-null     int64
 2   1991          55 non-null     int64
 3   1992          55 non-null     int64
 4   1993          55 non-null     int64
 5   1994          55 non-null     int64
 6   1995          55 non-null     int64
 7   1996          55 non-null     int64
 8   1997          55 non-null     int64
 9   1998          55 non-null     int64
 10  1999          55 non-null     int64
 11  2000          55 non-null     int64
 12  2001          55 non-null     int64
 13  2002          55 non-null     int64
 14  2003          55 non-null     int64
 15  2004          55 non-null     int64
 16  2005          55 non-null     int64
 17  2006          55 non-null     int64
 18  2007          55 non-null     int64
 19  2008          55 non-null     int64
 20  2009          55 non-null     int64
 21  2010          55 non-null     int64
 22  2011          55 non-null     int64
 23  2012          55 non-null     int64
 24  2013          55 non-null     int64
 25  2014          55 non-null     int64
 26  2015          55 non-null     int64
 27  2016          55 non-null     int64
 28  2017          55 non-null     int64
 29  2018          55 non-null     int64
 30  2019          55 non-null     int64
 31  Total_export  55 non-null     int64
dtypes: int64(31), str(1)
memory usage: 13.9 KB

========== Import ==========
<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       35 non-null     str
 1   1990          35 non-null     int64
 2   1991          35 non-null     int64
 3   1992          35 non-null     int64
 4   1993          35 non-null     int64
 5   1994          35 non-null     int64
 6   1995          35 non-null     int64
 7   1996          35 non-null     int64
 8   1997          35 non-null     int64
 9   1998          35 non-null     int64
 10  1999          35 non-null     int64
 11  2000          35 non-null     int64
 12  2001          35 non-null     int64
 13  2002          35 non-null     int64
 14  2003          35 non-null     int64
 15  2004          35 non-null     int64
 16  2005          35 non-null     int64
 17  2006          35 non-null     int64
 18  2007          35 non-null     int64
 19  2008          35 non-null     int64
 20  2009          35 non-null     int64
 21  2010          35 non-null     int64
 22  2011          35 non-null     int64
 23  2012          35 non-null     int64
 24  2013          35 non-null     int64
 25  2014          35 non-null     int64
 26  2015          35 non-null     int64
 27  2016          35 non-null     int64
 28  2017          35 non-null     int64
 29  2018          35 non-null     int64
 30  2019          35 non-null     int64
 31  Total_import  35 non-null     int64
dtypes: int64(31), str(1)
memory usage: 8.9 KB

========== Production ==========
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           55 non-null     str
 1   Coffee type       55 non-null     str
 2   1990/91           55 non-null     float64
 3   1991/92           55 non-null     float64
 4   1992/93           55 non-null     float64
 5   1993/94           55 non-null     float64
 6   1994/95           55 non-null     float64
 7   1995/96           55 non-null     float64
 8   1996/97           55 non-null     float64
 9   1997/98           55 non-null     float64
 10  1998/99           55 non-null     float64
 11  1999/00           55 non-null     float64
 12  2000/01           55 non-null     float64
 13  2001/02           55 non-null     float64
 14  2002/03           55 non-null     float64
 15  2003/04           55 non-null     float64
 16  2004/05           55 non-null     float64
 17  2005/06           55 non-null     float64
 18  2006/07           55 non-null     float64
 19  2007/08           55 non-null     float64
 20  2008/09           55 non-null     float64
 21  2009/10           55 non-null     float64
 22  2010/11           55 non-null     float64
 23  2011/12           55 non-null     float64
 24  2012/13           55 non-null     float64
 25  2013/14           55 non-null     float64
 26  2014/15           55 non-null     float64
 27  2015/16           55 non-null     float64
 28  2016/17           55 non-null     float64
 29  2017/18           55 non-null     float64
 30  2018/19           55 non-null     float64
 31  2019/20           55 non-null     float64
 32  Total_production  55 non-null     float64
dtypes: float64(31), str(2)
memory usage: 14.3 KB

In [8]:
# Q4: Are there any missing values?
for name, df in datasets.items():
    missing = df.isnull().sum()
    print(f"{name}: {missing.sum()} missing values in total")
    # Show only the columns that actually have missing values
    if missing.sum() > 0:
        print(missing[missing > 0])
    print()

Export: 0 missing values in total

Import: 0 missing values in total

Production: 0 missing values in total

In [9]:
# Q5: Which span of years is represented?
# Years are stored as column names (wide format), so find columns that start with 4 digits
for name, df in datasets.items():
    year_cols = [col for col in df.columns if str(col)[:4].isdigit()]
    print(f"{name}: {year_cols[0]} to {year_cols[-1]} ({len(year_cols)} year columns)")

Export: 1990 to 2019 (30 year columns)
Import: 1990 to 2019 (30 year columns)
Production: 1990/91 to 2019/20 (30 year columns)

In [10]:
# Q6: Which countries are included in the records?
country_col = "Country"  # change this if your column name is different

for name, df in datasets.items():
    countries = df[country_col].unique()
    print(f"--- {name}: {df[country_col].nunique()} countries ---")
    print(sorted(countries))

    print()

--- Export: 55 countries ---
['Angola', 'Bolivia (Plurinational State of)', 'Brazil', 'Burundi', 'Cameroon', 'Central African Republic', 'Colombia', 'Congo', 'Costa Rica', 'Cuba', "Côte d'Ivoire", 'Democratic Republic of Congo', 'Dominican Republic', 'Ecuador', 'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Gabon', 'Ghana', 'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'India', 'Indonesia', 'Jamaica', 'Kenya', "Lao People's Democratic Republic", 'Liberia', 'Madagascar', 'Malawi', 'Mexico', 'Nepal', 'Nicaragua', 'Nigeria', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Rwanda', 'Sierra Leone', 'Sri Lanka', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad & Tobago', 'Uganda', 'Venezuela', 'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe']

--- Import: 35 countries ---
['   Austria', '   Belgium', '   Belgium/Luxembourg', '   Bulgaria', '   Croatia', '   Cyprus', '   Czechia', '   Denmark', '   Estonia', '   Finland', '   France', '   Germany', '   Greece', '   Hungary', '   Ireland', '   Italy', '   Latvia', '   Lithuania', '   Luxembourg', '   Malta', '   Netherlands', '   Poland', '   Portugal', '   Romania', '   Slovakia', '   Slovenia', '   Spain', '   Sweden', 'Japan', 'Norway', 'Russian Federation', 'Switzerland', 'Tunisia', 'United Kingdom', 'United States of America']

--- Production: 55 countries ---
['Angola', 'Bolivia (Plurinational State of)', 'Brazil', 'Burundi', 'Cameroon', 'Central African Republic', 'Colombia', 'Congo', 'Costa Rica', 'Cuba', "Côte d'Ivoire", 'Democratic Republic of Congo', 'Dominican Republic', 'Ecuador', 'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Gabon', 'Ghana', 'Guatemala', 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'India', 'Indonesia', 'Jamaica', 'Kenya', "Lao People's Democratic Republic", 'Liberia', 'Madagascar', 'Malawi', 'Mexico', 'Nepal', 'Nicaragua', 'Nigeria', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Rwanda', 'Sierra Leone', 'Sri Lanka', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad & Tobago', 'Uganda', 'Venezuela', 'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe']

### Part 2 Answers

| Question | Export | Import | Production |
|---|---|---|---|
| Rows × columns | 55 × 32 | 35 × 32 | 55 × 33 |
| Column names | `Country`, `1990`–`2019`, `Total_export` | `Country`, `1990`–`2019`, `Total_import` | `Country`, `Coffee type`, `1990/91`–`2019/20`, `Total_production` |
| Data types | `Country` is text (`str`); 31 number columns are `int64` | `Country` is text (`str`); 31 number columns are `int64` | `Country` and `Coffee type` are text (`str`); 31 number columns are `float64` |
| Missing values | 0 | 0 | 0 |
| Year span | 1990–2019 (30 calendar years) | 1990–2019 (30 calendar years) | 1990/91–2019/20 (30 crop years) |
| Countries | 55 coffee-exporting countries | 35 importing countries | 55 coffee-producing countries |

**Notes**
- All three datasets are in **wide format**: each year is its own column instead of one `Year` column.
- The export and production files list producing countries (e.g., Brazil, Colombia, Ethiopia, Viet Nam). The import file lists consuming countries, mostly in Europe plus the United States of America.
- Production uses **crop years** (`1990/91`) and stores numbers as `float64`, while export and import use **calendar years** and `int64`. Comparing them directly will need some alignment.
- No values are missing, but some cells are `0`. These may hide missing data, which I will check in Part 4.
- In the import data, 28 country names (the EU members, e.g. `'   Austria'`) start with extra spaces, while the other 7 do not. Filtering or matching by country name will fail unless the spaces are removed.

# Part 3 – Descriptive Statistics

In [11]:
# Show large numbers with commas instead of scientific notation (e.g. 1.2e+09)
pd.set_option("display.float_format", "{:,.0f}".format)

# Descriptive statistics for all numerical columns
for name, df in datasets.items():
    print(f"========== {name} ==========")
    display(df.describe())

========== Export ==========

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
count,55,55,55,55,55,55,55,55,55,55,...,55,55,55,55,55,55,55,55,55,55
mean,"88,008,000","82,846,909","85,413,818","82,000,364","77,136,000","74,044,364","84,729,818","87,750,545","87,536,727","93,970,909",...,"111,476,727","118,301,455","118,438,909","46,277,025","46,955,570","132,362,182","130,388,727","138,104,727","60,218,843","2,851,331,801"
std,"183,288,972","201,917,973","203,156,595","185,204,909","171,903,256","147,103,224","163,404,376","176,112,921","183,664,660","214,625,510",...,"312,141,965","303,243,824","313,092,624","381,867,695","371,306,611","376,385,682","340,751,770","392,749,302","397,789,935","6,261,176,927"
min,0,0,0,0,0,0,0,0,0,0,...,0,0,0,"-2,147,483,648","-2,147,483,648",0,0,0,"-2,147,483,648","1,500,000"
25%,"4,020,000","3,960,000","2,310,000","2,220,000","1,860,000","2,370,000","1,680,000","2,220,000","1,800,000","2,220,000",...,"540,000","450,000","360,000","570,000","450,000","660,000","570,000","510,000","390,000","60,840,000"
50%,"15,780,000","9,300,000","9,960,000","13,080,000","9,180,000","12,000,000","9,360,000","12,180,000","12,840,000","18,060,000",...,"7,920,000","8,220,000","4,200,000","3,720,000","3,540,000","4,560,000","3,480,000","6,660,000","3,180,000","316,080,000"
75%,"105,570,000","85,020,000","79,710,000","78,180,000","84,990,000","89,700,000","105,510,000","90,480,000","90,990,000","94,140,000",...,"81,330,000","88,620,000","78,180,000","58,080,000","47,430,000","64,200,000","49,470,000","62,340,000","56,250,000","2,552,670,000"
max,"1,016,160,000","1,270,980,000","1,127,460,000","1,070,280,000","1,036,380,000","868,080,000","915,060,000","1,008,060,000","1,088,640,000","1,388,940,000",...,"2,028,360,000","1,712,940,000","1,899,060,000","1,565,820,000","1,316,640,000","2,056,140,000","1,855,500,000","2,138,220,000","1,644,000,000","33,807,709,056"

========== Import ==========

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
count,35,35,35,35,35,35,35,35,35,35,...,35,35,35,35,35,35,35,35,35,35
mean,"127,083,429","122,194,286","135,798,857","132,202,286","128,612,571","124,064,571","133,467,429","138,965,143","141,886,286","146,454,857",...,"191,679,429","194,010,857","198,733,714","205,760,571","208,080,000","218,796,000","216,109,714","222,762,857","231,332,571","5,069,693,143"
std,"254,348,799","243,539,251","269,035,399","242,480,752","217,853,001","218,891,070","241,514,440","250,039,147","254,844,681","271,528,315",...,"336,366,621","340,409,947","345,336,818","353,929,459","351,178,707","366,762,772","368,439,384","367,825,007","385,453,760","8,850,559,471"
min,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"29,700,000"
25%,"630,000","480,000","6,180,000","7,890,000","8,880,000","8,550,000","9,750,000","10,740,000","10,770,000","11,760,000",...,"21,510,000","21,630,000","23,730,000","24,990,000","25,950,000","28,350,000","26,130,000","29,370,000","29,460,000","557,310,000"
50%,"34,440,000","31,500,000","36,180,000","40,080,000","46,260,000","37,980,000","44,580,000","43,620,000","45,720,000","47,400,000",...,"57,120,000","64,560,000","63,780,000","63,600,000","62,640,000","68,040,000","65,640,000","69,600,000","73,200,000","1,640,040,000"
75%,"116,850,000","114,120,000","121,020,000","116,970,000","124,650,000","125,160,000","133,500,000","143,910,000","154,650,000","149,100,000",...,"227,610,000","230,070,000","228,390,000","250,050,000","266,580,000","294,990,000","301,710,000","324,240,000","327,240,000","5,841,240,000"
max,"1,260,420,000","1,190,400,000","1,376,340,000","1,159,740,000","970,260,000","1,026,420,000","1,166,700,000","1,220,580,000","1,261,800,000","1,364,760,000",...,"1,565,580,000","1,563,360,000","1,620,960,000","1,653,900,000","1,662,480,000","1,730,280,000","1,769,280,000","1,735,080,000","1,851,240,000","42,507,660,000"

========== Production ==========

,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,1998/99,1999/00,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
count,55,55,55,55,55,55,55,55,55,55,...,55,55,55,55,55,55,55,55,55,55
mean,"101,705,455","110,475,273","107,477,455","100,100,727","101,797,091","95,259,273","112,702,909","108,967,636","118,762,909","143,328,000",...,"154,174,909","164,928,000","167,900,727","163,962,545","170,319,273","177,074,182","178,574,182","188,141,455","180,057,818","4,104,269,455"
std,"251,087,494","266,846,602","302,218,031","248,934,369","251,032,798","185,868,047","260,219,213","243,014,501","314,233,707","401,259,112",...,"446,991,854","493,141,671","503,052,940","491,872,712","505,969,842","522,547,197","513,558,749","585,111,067","539,092,205","11,125,495,963"
min,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"1,080,000"
25%,"2,430,000","3,900,000","2,640,000","2,130,000","2,610,000","2,610,000","2,340,000","2,880,000","3,480,000","3,540,000",...,"1,980,000","1,710,000","2,010,000","2,250,000","2,310,000","1,890,000","2,160,000","2,190,000","2,280,000","81,990,000"
50%,"27,660,000","27,780,000","30,000,000","26,520,000","24,360,000","26,040,000","24,060,000","18,000,000","26,340,000","21,840,000",...,"20,940,000","20,040,000","15,480,000","14,880,000","17,580,000","16,200,000","15,840,000","18,600,000","18,420,000","623,640,000"
75%,"92,160,000","97,200,000","92,340,000","94,860,000","115,320,000","112,770,000","113,970,000","96,690,000","107,670,000","121,170,000",...,"97,350,000","91,890,000","71,850,000","69,600,000","66,570,000","68,640,000","70,530,000","78,060,000","71,940,000","2,785,140,000"
max,"1,637,160,000","1,637,580,000","2,076,180,000","1,690,020,000","1,691,520,000","1,083,600,000","1,751,820,000","1,568,880,000","2,205,660,000","2,854,680,000",...,"2,915,520,000","3,325,080,000","3,281,340,000","3,198,300,000","3,172,260,000","3,407,280,000","3,164,400,000","3,907,860,000","3,492,660,000","75,082,980,000"

In [12]:
# Key metric = the Total column (sum of all 30 years for each country)
for name, df in datasets.items():
    total_col = [col for col in df.columns if col.startswith("Total")][0]
    total = df[total_col]

    print(f"--- {name} ({total_col}) ---")
    print(f"Largest : {total.max():,.0f}  ({df.loc[total.idxmax(), 'Country'].strip()})")
    print(f"Smallest: {total.min():,.0f}  ({df.loc[total.idxmin(), 'Country'].strip()})")
    print(f"Average : {total.mean():,.0f}")
    print(f"Median  : {total.median():,.0f}")
    print()

--- Export (Total_export) ---
Largest : 33,807,709,056  (Brazil)
Smallest: 1,500,000  (Equatorial Guinea)
Average : 2,851,331,801
Median  : 316,080,000

--- Import (Total_import) ---
Largest : 42,507,660,000  (United States of America)
Smallest: 29,700,000  (Malta)
Average : 5,069,693,143
Median  : 1,640,040,000

--- Production (Total_production) ---
Largest : 75,082,980,000  (Brazil)
Smallest: 1,080,000  (Equatorial Guinea)
Average : 4,104,269,455
Median  : 623,640,000

In [13]:
# Top 5 countries by total, to see how concentrated the market is
for name, df in datasets.items():
    total_col = [col for col in df.columns if col.startswith("Total")][0]
    print(f"--- {name}: Top 5 ---")
    display(df.nlargest(5, total_col)[["Country", total_col]])

--- Export: Top 5 ---

      Country  Total_export
2      Brazil   33807709056
51   Viet Nam   24924480000
6    Colombia   19878480000
25  Indonesia   10607940000
24      India    6933960000

--- Import: Top 5 ---

                     Country  Total_import
34  United States of America   42507660000
11                   Germany   31481400000
15                     Italy   13272120000
28                     Japan   12422760000
10                    France   11972520000

--- Production: Top 5 ---

      Country  Total_production
2      Brazil    75,082,980,000
53   Viet Nam    28,803,180,000
23   Colombia    21,598,620,000
5   Indonesia    15,404,880,000
29   Ethiopia     8,669,520,000

In [14]:
# Look for impossible values: trade amounts can't be negative
year_cols = [col for col in exports.columns if col[:4].isdigit()]
negative_rows = exports[(exports[year_cols] < 0).any(axis=1)]
negative_rows[["Country", "2013", "2014", "2015", "2016", "Total_export"]]

  Country        2013        2014        2015        2016  Total_export
2  Brazil  1899060000 -2147483648 -2147483648  2056140000   33807709056

### Part 3 Answers

**Key metric:** the `Total` column of each dataset (sum of all 30 years per country).

| Dataset | Largest | Smallest | Average (mean) | Median |
|---|---|---|---|---|
| Export | 33,807,709,056 (Brazil) | 1,500,000 (Equatorial Guinea) | 2,851,331,801 | 316,080,000 |
| Import | 42,507,660,000 (United States of America) | 29,700,000 (Malta) | 5,069,693,143 | 1,640,040,000 |
| Production | 75,082,980,000 (Brazil) | 1,080,000 (Equatorial Guinea) | 4,104,269,455 | 623,640,000 |

**Observations and anomalies**
- **Brazil's exports in 2014 and 2015 are -2,147,483,648.** Exports can't be negative. This number is the smallest possible 32-bit integer, a common error code, so the real values are missing. Because `Total_export` adds these two values, Brazil's total is also wrong (about 4.3 billion too low).
- **The mean is much higher than the median** in all three datasets (export mean is about 9× the median). A few very large countries pull the average up, so the median describes a "typical" country better.
- **The market is very concentrated.** The top 5 countries make up about 61% of exports, 63% of imports, and 66% of production. Brazil alone produced about one-third of all coffee.
- The same four countries lead both export and production: Brazil, Viet Nam, Colombia, and Indonesia. The biggest importers are the United States of America and Germany.
- The minimum value in many year columns is **0**, so some countries have years with no recorded trade or production.

# Part 4 – Data Quality Assessment

In [15]:
# Check missing values, fully duplicated rows, and repeated country names
for name, df in datasets.items():
    print(f"{name}: missing = {df.isnull().sum().sum()}, "
          f"duplicate rows = {df.duplicated().sum()}, "
          f"repeated countries = {df['Country'].str.strip().duplicated().sum()}")

Export: missing = 0, duplicate rows = 0, repeated countries = 0
Import: missing = 0, duplicate rows = 0, repeated countries = 0
Production: missing = 0, duplicate rows = 0, repeated countries = 0

In [16]:
# Count how many years are recorded as 0 for each country
for name, df in datasets.items():
    year_cols = [col for col in df.columns if col[:4].isdigit()]
    zero_counts = (df[year_cols] == 0).sum(axis=1)
    has_zeros = df.loc[zero_counts > 0, "Country"].str.strip()

    print(f"--- {name}: {(zero_counts > 0).sum()} countries have 0 values ---")
    print(pd.Series(zero_counts[zero_counts > 0].values, index=has_zeros)
            .sort_values(ascending=False).head(5))
    print()

--- Export: 11 countries have 0 values ---
Country
Congo                23
Equatorial Guinea    20
Gabon                14
Nepal                13
Paraguay             11
dtype: int64

--- Import: 10 countries have 0 values ---
Country
Belgium/Luxembourg    21
Belgium                9
Luxembourg             9
Slovakia               3
Croatia                2
dtype: int64

--- Production: 7 countries have 0 values ---
Country
Equatorial Guinea    22
Nepal                13
Timor-Leste          10
Gabon                 8
Guyana                8
dtype: int64

In [17]:
# 1) Extra spaces in country names
spaces = imports["Country"] != imports["Country"].str.strip()
print(f"Import country names with extra spaces: {spaces.sum()}")

# 2) Country groups that changed over time
print(imports[imports["Country"].str.contains("Belgium|Luxembourg")]
      [["Country", "1997", "1998", "1999", "2000"]])

# 3) Two labels that may mean the same coffee type
print(production["Coffee type"].value_counts())

# 4) Different number types and year formats across files
print(f"\nExport years: {exports.columns[1]} ({exports['1990'].dtype}) | "
      f"Production years: {production.columns[2]} ({production['1990/91'].dtype})")

Import country names with extra spaces: 28
                  Country       1997       1998       1999       2000
1                 Belgium          0          0  180180000  209460000
2      Belgium/Luxembourg  152640000  214800000          0          0
18             Luxembourg          0          0    8700000   13920000
Coffee type
Arabica            22
Robusta            15
Robusta/Arabica    10
Arabica/Robusta     8
Name: count, dtype: int64

Export years: 1990 (int64) | Production years: 1990/91 (float64)

### Part 4 Answers

**Missing values and duplicates**
None of the three datasets have missing (`NaN`) values, duplicate rows, or repeated countries. However, "no missing values" does not mean the data is complete, because missing data is hidden in other forms (below).

| # | Issue | Where | Evidence | How it could break or bias analysis |
|---|---|---|---|---|
| 1 | **Error code instead of real values** | Export: Brazil, 2014–2015 | Value is `-2,147,483,648` (smallest 32-bit integer) | Brazil is the biggest exporter, so any total, average, or trend that includes these years is badly wrong. `Total_export` for Brazil is already about 4.3 billion too low. |
| 2 | **Zeros that may mean "no data"** | All three files | Export: 11 countries (Congo has 23 zero years). Import: 10 countries. Production: 7 countries | Some zeros happen before a country existed, like Timor-Leste (production 0 until 2000/01) and Croatia, Slovakia, and the Baltic states (import 0 in the early 1990s). Treating these as real zeros pulls averages down and creates fake growth when the numbers "start." |
| 3 | **Extra spaces in country names** | Import: 28 EU countries | `'   Germany'` instead of `'Germany'` | Filtering (`== "Germany"`) returns nothing, and merging with the export or production data by country fails silently. |
| 4 | **Country groups that changed** | Import: Belgium, Luxembourg | `Belgium/Luxembourg` has data until 1998, then becomes 0. `Belgium` and `Luxembourg` start in 1999 | Looking at one row alone shows a fake crash or a fake jump. The three rows have to be combined to see the real trend. |
| 5 | **Inconsistent category labels** | Production: `Coffee type` | `Arabica/Robusta` (8) vs. `Robusta/Arabica` (10) | If they mean "mixed," a `groupby` will split one group into two and make each look smaller. If the order means "main type first," that rule should be documented. |
| 6 | **Different year formats and types** | Production vs. export and import | Crop years `1990/91` as `float64` vs. calendar years `1990` as `int64` | Columns can't be matched directly when comparing production to exports for the same year. A crop year also covers parts of two calendar years. |
| 7 | **Wide format** | All three files | 30 year columns instead of one `Year` column | Hard to plot trends over time or filter by year. The data will likely need to be reshaped to long format with `melt()`. |

# Part 5 – Initial Insights

Which dataset appears to contain the most complete information?
 -  The **Production Dataset** contains the most complete information. It also includes an extra Coffee type column which gives more detail than the other two files. 

Which dataset looks like it will require the most extensive cleaning?
 - The **Import Dataset** required the most extensive cleaning. 28 of its 35 country names start with extra spaces, Belgium and Luxembourg are split into three rows that overlap in different years, and several countries show zeros in the early 1990s simply because they did not exist yet. 
 - The **Export Dataset** has critical single error. Brazil, the largest exporter, has an error code (-2,147,483,648) instead of real values for 2014 and 2015.

What specific types of business questions could these datasets help a global coffee corporation answer?
 - **Which countries have the most stable coffee production?**
   > By comparing changes in annual coffee production across countries, we can identify which countries have stable production and which experience large fluctuations. This can help companies choose reliable suppliers and establish stable, long-term supply contracts.